# Generated by Django 5.1.6 on 2025-02-24 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp_blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tour',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
